language: node_js
node_js:
  - '0.10'
before_script:
  - npm install -g bower grunt-cli
  - bower install
  - gem install sass
services:
  - mongodb
  - memcached
script:
  - grunt
after_success:
  - bash ./.travis/deploy_to_heroku.sh
